# Generated by Django 5.2.1 on 2025-07-04 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('web', 'Desarrollo Web'), ('data', 'Base de Datos'), ('ia', 'Inteligencia Artificial'), ('seguridad', 'Ciberseguridad')], max_length=50, verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='ActividadExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, verbose_name='Clave de la actividad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la actividad')),
                ('descripcion', models.TextField(help_text='Describe brevemente la actividad', verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso', verbose_name='Curso relacionado')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
